### ISSUE TITLE
from_filename() does not work with cargo

### ISSUE THREAD

**Issue by alicemaz** [slapresta/rust-dotenv#10]
by default cargo builds to and runs from `./target/debug/`, so the call to `current_exe()` returns that location rather than the one we want. proposing this be changed to `current_dir()` instead. I was planning on pull requesting this, just wanted to ask beforehand since I have no idea whether this would break anyone's workflow

**Comment by slapresta** [comment]
Oh, definitely! We made that change on the `dotenv` method already, and `dotenv` should be equivalent to calling `from_filename(".env")`. Feel free to do a pull request!

**Comment by slapresta** [comment]
@alicemaz Thanks for the pull request! Do you think `from_filename` should also call `current_dir` as well instead of `current_exe`? It makes sense to me.

**Comment by alicemaz** [comment]
@slapresta mmk, that one handles both the `current_exe()` thing and brings the two public functions into alignment. I'm personally a fan of the "special-case helper function does nothing but call a more general case" design and think doing that here fits well with the rest of the project's flow
