### ISSUE TITLE
Break out separate testing directory

### ISSUE THREAD

**Issue by mfpiccolo** [slapresta/rust-dotenv#15]
Break out a separate test directory in this repo would be useful for testing functionality.  I will put some effort into this if no one gets to it before me.

**Comment by slapresta** [comment]
Sounds good to me.

**Comment by slapresta** [comment]
Does #21 close this? @mfpiccolo

**Comment by mfpiccolo** [comment]
Yes #21 closes this issue.  Should have referenced it in the PR.  Thanks for reminding me.
