### ISSUE TITLE
Consider adding an optional `dotenv!` macro

### ISSUE THREAD

**Issue by sgrif** [slapresta/rust-dotenv#17]
This would of course only work on nightly (or using something like `syntex`). When using environment variables in tests, the value at compile time and runtime will always be the same. This could certainly help to reduce boilerplate needed to get an environment variable across multiple testing environments.

**Comment by slapresta** [comment]
I like the idea a lot, but I wouldn't even know where to start. Has anyone here played around with syntex and/or compiler plugins?

**Comment by mfpiccolo** [comment]
I have a bit.  I could give this a swing later tonight but @sgrif probably could nock this out on his lunch break.

**Comment by sgrif** [comment]
Yeah, I can open a PR if you like the idea. Do you want the same setup we did in [diesel_codegen](https://github.com/sgrif/diesel/tree/master/diesel_codegen)? (Assume syntex by default, nightly users can specify `default-features = false, features = ["nightly"]` to opt into `rustc_plugin`)

I'm also not positive if this can be done in the same crate (I've actually never tried). If not, we'd want to either create a new repo, or just put everything in separate directories like [diesel](https://github.com/sgrif/diesel) and [serde](https://github.com/serde-rs/serde)

@mfpiccolo I can pair on this one evening if you want to get more familiar with the codegen stuff

**Comment by mfpiccolo** [comment]
Yeah. That would be awesome @sgrif.  I got #[derive(Model)] for adding thread local connection (because I know you love that idea so much ;) ) working in a local crate last night but I basically just followed what you did with #[derive(Queriable)].  That Aster api makes my brain hurt a bit.  I would definitely appreciate a pair session.

**Comment by slapresta** [comment]
Closed by #23.
