### ISSUE TITLE
Look further than `Cargo.toml`'s directory by default

### ISSUE THREAD

**Issue by sgrif** [slapresta/rust-dotenv#18]
We have this code in a few places in Diesel. https://github.com/sgrif/diesel/blob/caea99a34e7846f4f1536c1454e94340ece256c0/diesel_tests/tests/schema.rs#L166-L168

It's pretty common for projects to have the code and tests as two crates (and sometimes more in the same repo), but want to share `.env`. Either looking one directory above `Cargo.toml`, or just continuing to recurse until either `.env` is found, or hitting root would help a very common use case.

**Comment by alicemaz** [comment]
I can put this together. partial to the latter. as far as I know cargo only looks in parents of the pwd for `Cargo.toml`/`.cargo` so recursing up from `current_dir()` should obviate the need to check `CARGO_MANIFEST_DIR`?

**Comment by sgrif** [comment]
Yeah, I'm partial to the latter as well.

**Comment by slapresta** [comment]
Should this be the default behaviour for `dotenv()` and/or `from_filename()`, or should this be a separate function or a flag? I'm not sure how common the opposite case (that is, projects that have several crates under the same hierarchy, but do not want to share `.env`s) is.

Thoughts? @sgrif @alicemaz

**Comment by sgrif** [comment]
I would expect it to be the default behavior. I wouldn't imagine that projects sharing a directory are likely to have a `.env` in the shared directory if they don't want to share `.env`s. I think every case that would be affected by this change would currently error today.

**Comment by slapresta** [comment]
Fair. Merging #19, then!
