### ISSUE TITLE
Return path to loaded file

### ISSUE THREAD

**Issue by alicemaz** [slapresta/rust-dotenv#22]
String is probably fine. I can't think of a use-case for PathBuf, though if anyone has one I don't see why not. I am a big "print everything important while debugging" person. could forsee this saving someone debugging annoyance at some point

(just putting this here to copy/paste into the readme. also ping #20 this is the one I meant)

```
match dotenv() {
    Ok(p) => println!("loaded {}", p),
    Err(_) => panic!("hey those envs are important")
}
```

**Comment by chills42** [comment]
This sounds like a nice improvement!  Just to be clear, this would mean a return type change for all of the loading methods from:
```rust
pub fn from_path(path: &Path) -> Result<(), DotenvError>
pub fn from_filename(filename: &str) -> Result<(), DotenvError>
pub fn dotenv() -> Result<(), DotenvError>

fn from_file(file: File) -> Result<(), DotenvError>
fn try_parent(path: &Path, filename: &str) -> Result<(), DotenvError>
```

to

```rust
pub fn from_path(path: &Path) -> Result<String, DotenvError>
pub fn from_filename(filename: &str) -> Result<String, DotenvError>
pub fn dotenv() -> Result<String, DotenvError>

fn from_file(file: File) -> Result<String, DotenvError>
fn try_parent(path: &Path, filename: &str) -> Result<String, DotenvError>
```

**Comment by slapresta** [comment]
This makes lots of sense to me! It's probably a good idea to get big changes like this one done before #20.

**Comment by mfpiccolo** [comment]
:+1:

**Comment by slapresta** [comment]
I'm closing this because _I think_ #59 covers it. Feel free to reopen if it isn't the case!
