### ISSUE TITLE
Proposal: Add functions which mirror `env::var` and `env::vars`

### ISSUE THREAD

**Issue by sgrif** [slapresta/rust-dotenv#33]
The implementation of these functions would use https://doc.rust-lang.org/nightly/std/sync/struct.Once.html to call `dotenv::dotenv()` the first time one of these functions are called (but not on subsequent calls), and then call `env::var` or `env::vars` respectively. I would expect this function to ignore errors that result from no `.env` file being present, but bubble up errors that result from the file failing to parse.

Thoughts?

**Comment by slapresta** [comment]
As a convenience wrapper, right? Sounds good to me.

**Comment by sgrif** [comment]
Looks like this was resolved in #47
