### ISSUE TITLE
Unreleased 0.9.0 version intentional?

### ISSUE THREAD

**Issue by carols10cents** [slapresta/rust-dotenv#41]
Hi! I just noticed that [the current version on github is 0.9.0](https://github.com/slapresta/rust-dotenv/blob/50e602046103f84c824bcc38f407c26e6fd058b5/Cargo.toml#L4), and at some point _after_ that in people-time (but not git-history-time), [there was an 0.8.1](https://github.com/slapresta/rust-dotenv/commit/50e602046103f84c824bcc38f407c26e6fd058b5), but the latest version I see in crates.io is 0.8.0.

Is the latest code intentionally unreleased?

**Comment by daboross** [comment]
@slapresta any update on this?

I'm using dotenv as a dev-dependency just for tests, so I don't really _need_ the latest version, but it might be nice to have some of the latest additions like the newer regex dependency and disallowing spaces in `.env` files. Thanks!

**Comment by steveklabnik** [comment]
Same here! It'd be nice to have the updated regex dependency.

**Comment by slapresta** [comment]
Thanks @carols10cents @daboross @steveklabnik! Version 0.9.0 should be published now. Feel free to reopen if any issues arise.

**Comment by steveklabnik** [comment]
Thank you so much! ❤️
