### ISSUE TITLE
required envvars and allowed values

### ISSUE THREAD

**Issue by hobofan** [slapresta/rust-dotenv#42]
One of the main reasons why I use `dotenv` libraries in other languages is that some of them provide the possibility to enforce that a envvar has been set and/or limit which values the envvar is allowed to have.

Would be nice to have this in this crate too.

Some inspiration:
[php dotenv](https://github.com/vlucas/phpdotenv#requiring-variables-to-be-set)
[figaro in ruby](https://github.com/laserlemon/figaro#required-keys)

**Comment by slapresta** [comment]
Sorry for never replying to this! :(

I feel like this is out-of-scope for our dotenv library. Perhaps this is better suited for a library that complements dotenv in giving you a consistent manner of accessing your configuration values, such as mehcode/config-rs?

**Comment by hobofan** [comment]
No problem :)

Yeah, I think that's a fair opinion.
