### ISSUE TITLE
Implement std::error::Error and std::fmt::Display for DotenvError

### ISSUE THREAD

**Issue by MoreAxes** [slapresta/rust-dotenv#48]
This would greatly aid writing generic code.

My specific use case is this (currently impossible):

```
IronError::new(err, format!("error: {}", err))
```

where `err: DotenvError`. `IronError`'s constructor here is `new<E: Error, M: Modifier<Response>>(e: E, m: M)`; the error gets stored in a `Box<Error + Send>` field.

**Comment by slapresta** [comment]
This makes sense to me. It's been pending since forever, I think.

**Comment by MoreAxes** [comment]
I actually had a go at implementing this, but eventually ran into a borrowck issue that I had no time to solve, so I just worked around it (by using my own Error struct in place of the DotenvError).
