### ISSUE TITLE
env strings which include a space

### ISSUE THREAD

**Issue by belst** [slapresta/rust-dotenv#49]
Hi,

in bash I would export a string which contains a space by wrapping it inside `""`. eg:
```
FOO="bar baz"
```

If I used this in the library the string I would get would contain the `""` though.
To use a space separated string in `.env` I would nee to do it like this:
```
FOO=bar baz
```

this would make the file unsourcable though. (command not found: baz)

example:
```
extern crate dotenv;
use std::env;

fn main() {
    dotenv::dotenv().ok();
    let foo = env::var("FOO").unwrap();
    println!("FOO: {}", foo);
}
```

`$ echo 'FOO="foo bar baz"' > .env`  
`$ cargo run`
```
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/bar`
FOO: "foo bar baz"
```
`$ rm .env`  
`$ FOO="foo bar baz" cargo run`
```
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/bar`
FOO: foo bar baz
```

Notice the `""`

**Comment by daboross** [comment]
This should be fixed as of dotenv 0.10, at least for me the test program you posted compiles and produces the correct output!

If this is still an issue, please comment and I will re-open.
