### ISSUE TITLE
0.3.0 release

### ISSUE THREAD

**Issue by chills42** [slapresta/rust-dotenv#5]
I think it would be good to go ahead and release the current version of master to crates.io with as ver. 0.3.0, which would get a working copy out for use.

Also, I think we can get docs built automatically after the release here:
https://github.com/arcnmx/youmu-docs/pull/6

**Comment by slapresta** [comment]
Will do!

**Comment by slapresta** [comment]
[Done!](https://crates.io/crates/dotenv)

**Comment by chills42** [comment]
Thanks, docs are available at: http://arcnmx.github.io/youmu-docs/dotenv/dotenv/
