### ISSUE TITLE
Consider making "key=" valid line

### ISSUE THREAD

**Issue by xliiv** [slapresta/rust-dotenv#54]
Now it's not, see:
https://github.com/slapresta/rust-dotenv/blob/master/src/lib.rs#L322

I think `"key="` could be a valid line, what do you think?

**Comment by dtolnay** [comment]
:+1: the Ruby dotenv gem supports this and gives you an empty string.

**Comment by slapresta** [comment]
Not necessarily for or against this, but if you want to set an empty string as a value, you can do `key=""`.

I imagine that this is more about being able to distribute a "fill-in-the-blanks" `.env` file and not failing when processing it, which is something we probably should play nice with.

**Comment by slapresta** [comment]
For reference, it seems to me that this behavior should be pretty easy to alter: https://github.com/slapresta/rust-dotenv/blob/master/src/lib.rs#L166
